# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Process Management
version: "0.0.1"
slug: example
description: Brings Process Management techniques into your smart home!
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
