# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-ubuntu:20.04"
  aarch64: "ghcr.io/home-assistant/aarch64-base-ubuntu:20.04"
  # armhf: "ghcr.io/home-assistant/armhf-base-ubuntu:20.04"
  # armv7: "ghcr.io/home-assistant/armv7-base-ubuntu:20.04"
  # i386: "ghcr.io/home-assistant/i386-base-ubuntu:18.04"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Process Management"
  org.opencontainers.image.description: "Process Management add-on for process mining in our smart home."
  org.opencontainers.image.source: "https://github.com/FelixMarschall/HA_ProcessMining_Addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
