# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Process Management
version: "1.0.0"
slug: example
description: Brings Process Management techniques into your smart home!
url: "https://github.com/FelixMarschall/HA_ProcessMining_Addon"
arch:
  #- armhf
  #- armv7
  - aarch64
  - amd64
  #- i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/felixmarschall/process-management-{arch}-addon"
webui: "[PROTO:option_name]://[HOST]:[PORT:8050]"
ports:
  8050/tcp: 8050
panel_title: "Process Management"
panel_icon: "mdi:graph"
#apparmor: false
